import { ClerkProvider, currentUser } from '@clerk/nextjs';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Topbar from '@/components/shared/Topbar';
import LeftSidebar from '@/components/shared/LeftSidebar';
import RightSidebar from '@/components/shared/RightSidebar';
import Bottombar from '@/components/shared/Bottombar';
import { fetchUser } from '@/lib/actions/user.action';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'TalkTalk',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const user = await currentUser();
	const user1 = await fetchUser(user?.id!);

	return (
		<ClerkProvider>
			<html lang='ru'>
				<body className={inter.className}>
					<Topbar />
					<main className='flex flex-row'>
						<LeftSidebar username={user1.username} />
						<section className='main-container'>
							<div className='w-full max-w-4xl text-white'>{children}</div>
						</section>
						<RightSidebar />
					</main>
					<Bottombar />
				</body>
			</html>
		</ClerkProvider>
	);
}
